on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - id: compile
        run: |
          docker run -v "$PWD":/build fredrikfornwall/rust-static-builder:1.44.1
          cd target/x86_64-unknown-linux-musl/release
          sudo zip config-env.zip config-env
          echo ::set-output name=VERSION::$(cat VERSION)

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.compile.outputs.VERSION }}
          release_name: Release ${{ steps.compile.outputs.VERSION }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-musl/release/config-env.zip
          asset_name: config-env.zip
          asset_content_type: application/zip
